/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type StudioSettings = {
  _id: string;
  _type: "studioSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  headline?: InternationalizedArrayString;
  subline?: InternationalizedArrayText;
  statement?: InternationalizedArrayRichText;
  portrait?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: InternationalizedArrayString;
    _type: "image";
  };
  email?: string;
  socials?: Array<{
    label?: string;
    url?: string;
    _key: string;
  }>;
  metadata?: Metadata;
};

export type Metadata = {
  _type: "metadata";
  title?: string;
  description?: string;
  keywords?: Array<string>;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  noIndex?: boolean;
};

export type InternationalizedArrayString = Array<
  {
    _key: string;
  } & InternationalizedArrayStringValue
>;

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type InternationalizedArrayRichText = Array<
  {
    _key: string;
  } & InternationalizedArrayRichTextValue
>;

export type InternationalizedArrayText = Array<
  {
    _key: string;
  } & InternationalizedArrayTextValue
>;

export type Navigation = {
  _id: string;
  _type: "navigation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  socials?: Array<{
    logo?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    socialMedia?: Link;
    _type: "socialLink";
    _key: string;
  }>;
};

export type PageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "page";
};

export type ArticleReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "article";
};

export type Link = {
  _type: "link";
  linkType?: "internal" | "external";
  internalLink?: PageReference | ArticleReference;
  externalUrl?: string;
  text?: string;
  openInNewTab?: boolean;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: InternationalizedArrayString;
  slug?: Slug;
  cover?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: InternationalizedArrayString;
    _type: "image";
  };
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: InternationalizedArrayString;
    _type: "image";
    _key: string;
  }>;
  client?: string;
  year?: number;
  medium?: InternationalizedArrayString;
  dimensions?: string;
  body?: InternationalizedArrayRichText;
  order?: number;
  featured?: boolean;
  span?: 6 | 12;
  publishedAt?: string;
  metadata?: Metadata;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type RichText = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<
        {
          _key: string;
        } & Link
      >;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      caption?: string;
      _type: "image";
      _key: string;
    }
>;

export type Article = {
  _id: string;
  _type: "article";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  slug?: Slug;
  author?: string;
  publishedAt?: string;
  metadata?: Metadata;
  title?: string;
  excerpt?: string;
  featuredImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  content?: RichText;
  categories?: Array<string>;
  tags?: Array<string>;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  slug?: Slug;
  publishedAt?: string;
  metadata?: Metadata;
  title?: string;
  content?: RichText;
  link?: Link;
};

export type InternationalizedArrayRichTextValue = {
  _type: "internationalizedArrayRichTextValue";
  value?: RichText;
  language?: string;
};

export type InternationalizedArrayTextValue = {
  _type: "internationalizedArrayTextValue";
  value?: string;
  language?: string;
};

export type InternationalizedArrayStringValue = {
  _type: "internationalizedArrayStringValue";
  value?: string;
  language?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | StudioSettings
  | Metadata
  | InternationalizedArrayString
  | SanityImageCrop
  | SanityImageHotspot
  | InternationalizedArrayRichText
  | InternationalizedArrayText
  | Navigation
  | PageReference
  | ArticleReference
  | Link
  | Project
  | Slug
  | RichText
  | Article
  | Page
  | InternationalizedArrayRichTextValue
  | InternationalizedArrayTextValue
  | InternationalizedArrayStringValue
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: queries.ts
// Variable: pageQuery
// Query: *[_type == "page" && slug.current == $slug][0] {    _id,    title,    slug,      content[]{    ...,    markDefs[]{      ...,      _type == "link" => {        ...,        internalLink->{_type, slug, title}      }    }  },      link {    ...,    internalLink->{_type, slug, title}  },    metadata,    publishedAt,    _updatedAt  }
export type PageQueryResult = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  content: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
        listItem?: "bullet" | "number";
        markDefs: Array<{
          _key: string;
          _type: "link";
          linkType?: "external" | "internal";
          internalLink:
            | {
                _type: "article";
                slug: Slug | null;
                title: string | null;
              }
            | {
                _type: "page";
                slug: Slug | null;
                title: string | null;
              }
            | null;
          externalUrl?: string;
          text?: string;
          openInNewTab?: boolean;
        }> | null;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        _type: "image";
        _key: string;
        markDefs: null;
      }
  > | null;
  link: {
    _type: "link";
    linkType?: "external" | "internal";
    internalLink:
      | {
          _type: "article";
          slug: Slug | null;
          title: string | null;
        }
      | {
          _type: "page";
          slug: Slug | null;
          title: string | null;
        }
      | null;
    externalUrl?: string;
    text?: string;
    openInNewTab?: boolean;
  } | null;
  metadata: Metadata | null;
  publishedAt: string | null;
  _updatedAt: string;
} | null;

// Source: queries.ts
// Variable: articleQuery
// Query: *[_type == "article" && slug.current == $slug][0] {    _id,    title,    slug,    excerpt,    featuredImage,      content[]{    ...,    markDefs[]{      ...,      _type == "link" => {        ...,        internalLink->{_type, slug, title}      }    }  },    categories,    tags,    author,    publishedAt,    metadata,    _updatedAt  }
export type ArticleQueryResult = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  excerpt: string | null;
  featuredImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  content: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
        listItem?: "bullet" | "number";
        markDefs: Array<{
          _key: string;
          _type: "link";
          linkType?: "external" | "internal";
          internalLink:
            | {
                _type: "article";
                slug: Slug | null;
                title: string | null;
              }
            | {
                _type: "page";
                slug: Slug | null;
                title: string | null;
              }
            | null;
          externalUrl?: string;
          text?: string;
          openInNewTab?: boolean;
        }> | null;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        _type: "image";
        _key: string;
        markDefs: null;
      }
  > | null;
  categories: Array<string> | null;
  tags: Array<string> | null;
  author: string | null;
  publishedAt: string | null;
  metadata: Metadata | null;
  _updatedAt: string;
} | null;

// Source: queries.ts
// Variable: allArticlesQuery
// Query: *[_type == "article"] | order(publishedAt desc) {    _id,    title,    slug,    excerpt,    featuredImage,    categories,    publishedAt  }
export type AllArticlesQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  excerpt: string | null;
  featuredImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  categories: Array<string> | null;
  publishedAt: string | null;
}>;

// Source: queries.ts
// Variable: projectsQuery
// Query: *[_type == "project"] | order(order asc, publishedAt desc) {      _id,  slug,  year,  client,  span,  featured,  cover,  "title": coalesce(title[_key == $locale][0].value, title[_key == "en"][0].value),  "medium": coalesce(medium[_key == $locale][0].value, medium[_key == "en"][0].value),  "coverAlt": coalesce(cover.alt[_key == $locale][0].value, cover.alt[_key == "en"][0].value)  }
export type ProjectsQueryResult = Array<{
  _id: string;
  slug: Slug | null;
  year: number | null;
  client: string | null;
  span: 12 | 6 | null;
  featured: boolean | null;
  cover: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: InternationalizedArrayString;
    _type: "image";
  } | null;
  title: string | null;
  medium: string | null;
  coverAlt: string | null;
}>;

// Source: queries.ts
// Variable: featuredProjectsQuery
// Query: *[_type == "project" && featured == true] | order(order asc, publishedAt desc) {      _id,  slug,  year,  client,  span,  featured,  cover,  "title": coalesce(title[_key == $locale][0].value, title[_key == "en"][0].value),  "medium": coalesce(medium[_key == $locale][0].value, medium[_key == "en"][0].value),  "coverAlt": coalesce(cover.alt[_key == $locale][0].value, cover.alt[_key == "en"][0].value)  }
export type FeaturedProjectsQueryResult = Array<{
  _id: string;
  slug: Slug | null;
  year: number | null;
  client: string | null;
  span: 12 | 6 | null;
  featured: true;
  cover: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: InternationalizedArrayString;
    _type: "image";
  } | null;
  title: string | null;
  medium: string | null;
  coverAlt: string | null;
}>;

// Source: queries.ts
// Variable: projectQuery
// Query: *[_type == "project" && slug.current == $slug][0] {      _id,  slug,  year,  client,  span,  featured,  cover,  "title": coalesce(title[_key == $locale][0].value, title[_key == "en"][0].value),  "medium": coalesce(medium[_key == $locale][0].value, medium[_key == "en"][0].value),  "coverAlt": coalesce(cover.alt[_key == $locale][0].value, cover.alt[_key == "en"][0].value),    dimensions,    publishedAt,    metadata,    _updatedAt,    "body": coalesce(body[_key == $locale][0].value, body[_key == "en"][0].value)[]{      ...,      markDefs[]{        ...,        _type == "link" => {          ...,          internalLink->{_type, slug, title}        }      }    },    gallery[]{      ...,      "alt": coalesce(alt[_key == $locale][0].value, alt[_key == "en"][0].value)    }  }
export type ProjectQueryResult = {
  _id: string;
  slug: Slug | null;
  year: number | null;
  client: string | null;
  span: 12 | 6 | null;
  featured: boolean | null;
  cover: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: InternationalizedArrayString;
    _type: "image";
  } | null;
  title: string | null;
  medium: string | null;
  coverAlt: string | null;
  dimensions: string | null;
  publishedAt: string | null;
  metadata: Metadata | null;
  _updatedAt: string;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
        listItem?: "bullet" | "number";
        markDefs: Array<{
          _key: string;
          _type: "link";
          linkType?: "external" | "internal";
          internalLink:
            | {
                _type: "article";
                slug: Slug | null;
                title: string | null;
              }
            | {
                _type: "page";
                slug: Slug | null;
                title: string | null;
              }
            | null;
          externalUrl?: string;
          text?: string;
          openInNewTab?: boolean;
        }> | null;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        _type: "image";
        _key: string;
        markDefs: null;
      }
  > | null;
  gallery: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | null;
    _type: "image";
    _key: string;
  }> | null;
} | null;

// Source: queries.ts
// Variable: projectSlugsQuery
// Query: *[_type == "project" && defined(slug.current)].slug.current
export type ProjectSlugsQueryResult = Array<string | null>;

// Source: queries.ts
// Variable: studioSettingsQuery
// Query: *[_type == "studioSettings"][0] {    _id,    name,    email,    socials,    portrait,    metadata,    "headline": coalesce(headline[_key == $locale][0].value, headline[_key == "en"][0].value),    "subline": coalesce(subline[_key == $locale][0].value, subline[_key == "en"][0].value),    "portraitAlt": coalesce(portrait.alt[_key == $locale][0].value, portrait.alt[_key == "en"][0].value),    "statement": coalesce(statement[_key == $locale][0].value, statement[_key == "en"][0].value)  }
export type StudioSettingsQueryResult = {
  _id: string;
  name: string | null;
  email: string | null;
  socials: Array<{
    label?: string;
    url?: string;
    _key: string;
  }> | null;
  portrait: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: InternationalizedArrayString;
    _type: "image";
  } | null;
  metadata: Metadata | null;
  headline: string | null;
  subline: string | null;
  portraitAlt: string | null;
  statement: RichText | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "page" && slug.current == $slug][0] {\n    _id,\n    title,\n    slug,\n    \n  content[]{\n    ...,\n    markDefs[]{\n      ...,\n      _type == "link" => {\n        ...,\n        internalLink->{_type, slug, title}\n      }\n    }\n  }\n,\n    \n  link {\n    ...,\n    internalLink->{_type, slug, title}\n  }\n,\n    metadata,\n    publishedAt,\n    _updatedAt\n  }\n': PageQueryResult;
    '\n  *[_type == "article" && slug.current == $slug][0] {\n    _id,\n    title,\n    slug,\n    excerpt,\n    featuredImage,\n    \n  content[]{\n    ...,\n    markDefs[]{\n      ...,\n      _type == "link" => {\n        ...,\n        internalLink->{_type, slug, title}\n      }\n    }\n  }\n,\n    categories,\n    tags,\n    author,\n    publishedAt,\n    metadata,\n    _updatedAt\n  }\n': ArticleQueryResult;
    '\n  *[_type == "article"] | order(publishedAt desc) {\n    _id,\n    title,\n    slug,\n    excerpt,\n    featuredImage,\n    categories,\n    publishedAt\n  }\n': AllArticlesQueryResult;
    '\n  *[_type == "project"] | order(order asc, publishedAt desc) {\n    \n  _id,\n  slug,\n  year,\n  client,\n  span,\n  featured,\n  cover,\n  "title": coalesce(title[_key == $locale][0].value, title[_key == "en"][0].value),\n  "medium": coalesce(medium[_key == $locale][0].value, medium[_key == "en"][0].value),\n  "coverAlt": coalesce(cover.alt[_key == $locale][0].value, cover.alt[_key == "en"][0].value)\n\n  }\n': ProjectsQueryResult;
    '\n  *[_type == "project" && featured == true] | order(order asc, publishedAt desc) {\n    \n  _id,\n  slug,\n  year,\n  client,\n  span,\n  featured,\n  cover,\n  "title": coalesce(title[_key == $locale][0].value, title[_key == "en"][0].value),\n  "medium": coalesce(medium[_key == $locale][0].value, medium[_key == "en"][0].value),\n  "coverAlt": coalesce(cover.alt[_key == $locale][0].value, cover.alt[_key == "en"][0].value)\n\n  }\n': FeaturedProjectsQueryResult;
    '\n  *[_type == "project" && slug.current == $slug][0] {\n    \n  _id,\n  slug,\n  year,\n  client,\n  span,\n  featured,\n  cover,\n  "title": coalesce(title[_key == $locale][0].value, title[_key == "en"][0].value),\n  "medium": coalesce(medium[_key == $locale][0].value, medium[_key == "en"][0].value),\n  "coverAlt": coalesce(cover.alt[_key == $locale][0].value, cover.alt[_key == "en"][0].value)\n,\n    dimensions,\n    publishedAt,\n    metadata,\n    _updatedAt,\n    "body": coalesce(body[_key == $locale][0].value, body[_key == "en"][0].value)[]{\n      ...,\n      markDefs[]{\n        ...,\n        _type == "link" => {\n          ...,\n          internalLink->{_type, slug, title}\n        }\n      }\n    },\n    gallery[]{\n      ...,\n      "alt": coalesce(alt[_key == $locale][0].value, alt[_key == "en"][0].value)\n    }\n  }\n': ProjectQueryResult;
    '\n  *[_type == "project" && defined(slug.current)].slug.current\n': ProjectSlugsQueryResult;
    '\n  *[_type == "studioSettings"][0] {\n    _id,\n    name,\n    email,\n    socials,\n    portrait,\n    metadata,\n    "headline": coalesce(headline[_key == $locale][0].value, headline[_key == "en"][0].value),\n    "subline": coalesce(subline[_key == $locale][0].value, subline[_key == "en"][0].value),\n    "portraitAlt": coalesce(portrait.alt[_key == $locale][0].value, portrait.alt[_key == "en"][0].value),\n    "statement": coalesce(statement[_key == $locale][0].value, statement[_key == "en"][0].value)\n  }\n': StudioSettingsQueryResult;
  }
}
