/**
 * Sanity Schema Types
 *
 * All schema definitions for Sanity CMS, organized in a flat structure.
 */

import type { SchemaTypeDefinition } from 'sanity'

import { article } from './article'
// Import all schema definitions
import { link } from './link'
import { metadata } from './metadata'
import { navigation } from './navigation'
import { page } from './page'
import { project } from './project'
import { richText } from './richText'
import { studioSettings } from './studioSettings'

// Re-export all schemas for convenience
export {
  article,
  link,
  metadata,
  navigation,
  page,
  project,
  richText,
  studioSettings,
}

// Schema collection for Sanity configuration
export const schema = {
  types: [
    // Object types (reusable components)
    link,
    metadata,
    richText,

    // Localized field types are NOT declared here: they are generated by
    // sanity-plugin-internationalized-array in `sanity.config.ts` from its
    // `fieldTypes` list. Declaring them again would collide.

    // Document types (content pages)
    page,
    article,
    project,

    // Singleton types (one-off content)
    navigation,
    studioSettings,
  ],
} satisfies { types: SchemaTypeDefinition[] }
